### ISSUE TITLE
msvcrt-ruby18.dll not found

### ISSUE THREAD

**Issue by Ajaxy** [socky/socky-server-ruby#1]
i got this trying to install Socky.
does it work with Ruby 1.9 and Rails 3.0?
thank you.

**Comment by imanel** [comment]
Could you provide more details? When this error happens - on start, connection or some specific case? Checking em-websockets bug I found you are using ruby 1.9.2 from rubyinstaller, but nothing else I know - what version of gems you have have? I assume eventmachine beta, but please specify versions of em-http-request and json. If possible also full stacktrace would be helpful.

**Comment by imanel** [comment]
Ok - I've found the problem. It's because json binary gem is built against ruby 1.8, and you need to recompile it.

gem uninstall json
gem install json --platform=ruby

About question with 1.9 and Rails 3 - yes it is working with them.

**Comment by imanel** [comment]
Created wiki page - please check
https://github.com/socky/socky-server-ruby/wiki/FAQ
