### ISSUE TITLE
Allow users to authenticate without calling back webserver

### ISSUE THREAD

**Issue by imanel** [socky/socky-server-ruby#10]
Currently to authenticate user we need to call back webserver. This is slowing everything down, and probably will be very hard to implement in cloud(optional server for people that will not be able to run own server - like deploy on Heroku) This also preventing us to fast subscribe/unsubscribe channel from user, and running Socky on static page. That's why authentication should be based on secret key(one per channel) like [pusher](https://github.com/newbamboo/pusher-gem) do. Problem is that we need to allow both private and public channels, and if we stop supporting callbacks to server then we will need to implement some kind of presence channel - or just enable "presence mode" for all channels(probably best option when implementing, but will raise data transfer a little)

**Comment by stefanoverna** [comment]
+1 on this. Pusher authentication solution is definitely the way to go. Any timing estimate on this?

Thank you for all your hard work, btw.
