### ISSUE TITLE
Socky demo not working on chrome 14.0.835.0 and Firefox Aurora 7.0a2

### ISSUE THREAD

**Issue by bhavinkamani** [socky/socky-server-ruby#15]
While trying to test Socky demo on latest Chrome and FF, I did not see any output. First page accepts my nick and displays a a second page with blank chat window. Subsequent message sends does not get displayed.

On the chrome console it displays multiple `"Unexpected response Code: 400" errors.`

On Firefox I get following error.

```
socky.min.js (line 11)
"NetworkError: 400 Bad request - http://ws.socky.org:8080/?client_id=dd"
ws.socky.org:8080
Firefox can't establish a connection to the server at ws://ws.socky.org:8080/?client_id=dd.
Socky.prototype.connect=function(){var...NTICATING;this.respond_to_connect()}; 
```

I am not able to make Socky work even on my machine. Here I 
1. installed Socky Server
2. configured rails by executing steps laid out as per  [Socky Home Page](http://imanel.org/projects/socky/)\
3. inserted <%= javascript_include_tag :socky %> and <%= socky %>  in index page
4. started Socky Server
5. started rails server
6. went to the rails server index page in chrome/ff
7. started rails console in another terminal and entered Socky.send "alert('Hi');"
8. Received `true` in rails console. But after that did not see anything happening at the browser page

**Comment by imanel** [comment]
Could you post Chrome net-internals content for me? Open [chrome://net-internals/#events](chrome://net-internals/#events) in your browser and type 'ws://' into filter. At the very bottom you will find one with description 'http://ws.socky.org:8080/?client_id=dd' (or with other client_in you are using as login) Most probably WebSocket version was updated to unsupported one and I need to know which it is to investigate further.

**Comment by bhavinkamani** [comment]
Thanks for your reply.

Not sure why but about:net-internals / chrome://net-internals/#events seems
to be broken. I dont see any data in that page. Moreover tabs in the page
were not rendered properly (based on screenshot of the page I have seen
while browsing). I restarted chrome but got similar results.

Any idea on what could have gone wrong or any other means of getting the
info on Websocket version?
- Bhavin

**Comment by imanel** [comment]
```
Sec-WebSocket-Version: 8
```

This is in logs. At this moment em-websocket(which Socky is basing on) is only supporting drafts up to 6. I can see pull request(igrigorik/em-websocket#51) for draft 8 and most probably that will be good place to start.

When em-websocket will receive update of supported version then Socky will start working with it OOTB.

Redirected to upstream - closing.

**Comment by bhavinkamani** [comment]
thanks imanel

**Comment by bhavinkamani** [comment]
Hi Imanel, 

Just noticed that EM-websocket has a new 0.3.1 release with changes to make it compatible with newer chrome and ff changes. Will socky work as it is by changing the gemspec dependencies or anything needs to be changed?

Thanks
Bhavin

**Comment by imanel** [comment]
Just update em-websocket to 0.3.1 and restart socky server and everything will work OOTB. I just updated demo server and it should now work with new Chrome and FF - please let me know if everything works :)

**Comment by bhavinkamani** [comment]
Works great.... Thanks a ton :-)  Socky is just amazing... loved it...

**Comment by Sabyasachig** [comment]
its working fine in local machine but in client machine it shows nothing
and in mozila it shows an error

WebSocket] cannot connect to Web Socket server at ws://mychat.com:8080/
(SecurityError) make sure the server is running and Flash socket policy
file is correctly placed
console.error(decodeURIComponent(message));
web_socket.js (line 380)
[WebSocket] close
[WebSocket] cannot connect to Web Socket server at ws://mychat.com:8080/
(SecurityError) make sure the server is running and Flash socket policy
file is correctly placed
webSocketError()web_socket.js (line 380)
message = "%5BWebSocket%5D%20canno...is%20correctly%20placed"

**Comment by imanel** [comment]
Have you tried to run [flash policy server](http://www.adobe.com/devnet/flashplayer/articles/socket_policy_files.html)? This will be needed for WebSocket in new Firefox(they have some problems with built-in policy server)

**Comment by Sabyasachig** [comment]
no i did not. can u help me how an i run this flash policy server

**Comment by imanel** [comment]
On mentioned site there is sample file "flashpolicyd" - please download it and unzip. Inside you will find everything needed to run standalone server or init script, along with readme describing how to use it. This is good to have for every flash site, but in Firefox it will also help to avoid policy file errors.

**Comment by Sabyasachig** [comment]
thanks let me try. I shall inform u about the status.

On Thu, Nov 24, 2011 at 7:31 PM, Bernard Potocki <
reply@reply.github.com

**Comment by Sabyasachig** [comment]
Imanel when i have tried to run the policy file it shows an error
./flashpolicy.xml: line 1: ?xml: No such file or directory
./flashpolicy.xml: line 2: !DOCTYPE: No such file or directory
./flashpolicy.xml: line 3: $'\r': command not found
./flashpolicy.xml: line 4: !--: No such file or directory
./flashpolicy.xml: line 5: cross-domain-policy: No such file or directory
./flashpolicy.xml: line 6: $'\r': command not found
./flashpolicy.xml: line 7: !--: No such file or directory
./flashpolicy.xml: line 8: !--: No such file or directory
./flashpolicy.xml: line 9: site-control: No such file or directory
./flashpolicy.xml: line 10: $'\r': command not found
./flashpolicy.xml: line 11: unexpected EOF while looking for matching `''
./flashpolicy.xml: line 17: syntax error: unexpected end of file

**Comment by imanel** [comment]
Could you share command you are running?

**Comment by Sabyasachig** [comment]
This is the command
sabyasachig@sabyasachig-u11:~/rails_chat_apps/EmWebsocketChatDemo/flashpolicyd$
./Standalone/flashpolicyd.py --file=./flashpolicy.xml --port=843
Listening on port 843

[Errno 13] Permission denied

On Fri, Nov 25, 2011 at 11:43 AM, Bernard Potocki <
reply@reply.github.com

**Comment by imanel** [comment]
This command need to be started with root privileges as all commands that is trying to use port below 1000. This program is secure, so don't be afraid, and it will be only required to run it once per server for all flash applications(not only Socky)

**Comment by Sabyasachig** [comment]
Thanks now its working. but again it arise a peculiar problem no client
machine can access my application. because of request time out. I m using
mongrel server.

On Fri, Nov 25, 2011 at 11:59 AM, Bernard Potocki <
reply@reply.github.com

**Comment by imanel** [comment]
Please read "Which Rack servers are currently supported?" section. At this moment only Thin server is supported - most other servers are single-request so connecting via websocket will block any other request. Thin is also much faster than mongrel so I would recommend using it :)

**Comment by Sabyasachig** [comment]
thin server is not working for this application it shows an error

> > Thin web server (v1.3.1 codename Triple Espresso)
> > Maximum connections set to 1024
> > Listening on 0.0.0.0:3000, CTRL+C to stop
> > !! Unexpected error while processing request: undefined method `debug_rjs='
> > for ActionView::Base:Class

On Fri, Nov 25, 2011 at 12:22 PM, Bernard Potocki <
reply@reply.github.com

**Comment by imanel** [comment]
https://github.com/rails/prototype-rails/issues/1

**Comment by Sabyasachig** [comment]
same problem for thin server also in client machine it shows request time
out page can not be retrieved

 can i send u my application as a zip

On Fri, Nov 25, 2011 at 2:37 PM, Bernard Potocki <
reply@reply.github.com

**Comment by imanel** [comment]
Feel free - my email is in profile. I will look and see what is happening:)

**Comment by maxkazar** [comment]
Chrome 16.0.912.63. Socky demo, after login in chat window show:

```
Connecting...
Connection closed
```

Browser console log:

```
Socky Websockets driver loaded
Socky connecting ws://ws.socky.org:8081/websocket/chat_app
Socky disconnected
Socky received message {"event":"socky:connection:closed"}
Socky received message {"event":"socky:connection:error","reason":"down"}
```

chrome://net-internals/#events:

```
ws://ws.socky.org:8081/websocket/chat_app

Start Time: Thu Jan 05 2012 15:19:43 GMT+0400 (MSK)

(P) t=1325762383782 [st=  0] +REQUEST_ALIVE             [dt=397]
(P) t=1325762383782 [st=  0]    +SOCKET_STREAM_CONNECT  [dt=196]
                                 --> url = "ws://ws.socky.org:8081/websocket/chat_app"
(P) t=1325762383782 [st=  0]       +PROXY_SERVICE       [dt=  0]
(P) t=1325762383782 [st=  0]           PROXY_SERVICE_RESOLVED_PROXY_LIST  
                                       --> pac_string = "DIRECT"
(P) t=1325762383782 [st=  0]       -PROXY_SERVICE       
(P) t=1325762383782 [st=  0]       +PROXY_SERVICE       [dt=  0]
(P) t=1325762383782 [st=  0]           PROXY_SERVICE_RESOLVED_PROXY_LIST  
                                       --> pac_string = "DIRECT"
(P) t=1325762383782 [st=  0]       -PROXY_SERVICE       
(P) t=1325762383782 [st=  0]        HOST_RESOLVER_IMPL  [dt=  1]
                                    --> source_dependency = {"id":9783,"type":7}
(P) t=1325762383978 [st=196]    -SOCKET_STREAM_CONNECT  
(P) t=1325762383979 [st=197]     WEB_SOCKET_SEND_REQUEST_HEADERS  
                                 --> GET /websocket/chat_app HTTP/1.1
                                     Upgrade: websocket
                                     Connection: Upgrade
                                     Host: ws.socky.org:8081
                                     Origin: http://demo.socky.org
                                     Sec-WebSocket-Key: oWboMKuGwHaCVoLP4SuXsQ==
                                     Sec-WebSocket-Version: 13
                                     Cookie: [value was stripped]


(P) t=1325762383979 [st=197]     SOCKET_STREAM_SENT     
(P) t=1325762384179 [st=397] -REQUEST_ALIVE 
```

When i try to test my application, i can send message to channel, and thin log show than message receive, but don't send message back

**Comment by imanel** [comment]
My bad - I've forgotten to update server app. It is working now.
Thanks for reporting!
