### ISSUE TITLE
Suscribing client_id: it is always a string

### ISSUE THREAD

**Issue by ccastillop** [socky/socky-server-ruby#2]
Hello,
I spent several hours trying to connect one client to another. Finnally, I realized that I was sending an integer at client_id. It must be a String, always. 
Guessing in somewhere of documentation I read that I can use String or Integers..,. :(

**Comment by imanel** [comment]
https://github.com/socky/socky-client-ruby/wiki/Usage

Client require you to pass "string or array of strings". The reason of that is that server will always receive client_id as string and we can't determine if it was integer or string at start. Is this resolve your question or I misunderstood it?

**Comment by ccastillop** [comment]
Thats fine, I have a mistake. But thank you, the gem is awesome  and now it is working fine. Thank you very much.
